googleAnalytics: ""
baseUrl: https://alpaca.markets/docs
languageCode: en-us
title: Alpaca Docs
theme: book

menu:
  # before: []

params:
  BookTheme: light
  BookSearch: true
  # BookMenuBundle: /menu
  BookLogo: "alpaca_icon@1x.png"
  BookSection: "/"
  BookRepo: "https://github.com/alpacahq/alpaca-docs-merge"
  BookEditPath: "edit/master"