googleAnalytics = ""
# baseURL = "http://example.org/"
baseUrl = "/"
languageCode = "en-us"
title = "Alpaca Docs"
theme = 'book'

[params]
    BookTheme = 'dark'
    BookSearch = true
    BookLogo = 'logo.png'
    BookRepo = 'https://github.com/alpacahq/bkdocs'
    BookEditPath = 'edit/master/bkdocs'

