baseUrl: "/"
languageCode: en-us
title: Alpaca Broker API Guide
theme: book

menu:

params:
  BookTheme: light
  BookSearch: true
  # BookMenuBundle: /menu
  BookLogo: 'alpaca_icon@1x.png'
  BookRepo: 'https://github.com/alpacahq/bkdocs'
  BookEditPath: 'edit/master/bkdocs'
